name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.6.3
      with:
        command: 'cd services/hqm-ranked-backend && ls && ./deploy.sh'
        host: 'hqmfun.space'
        username: root
        port: 22
        password: animal
